const List<String> prefixWords = [
  'Последний',
  'Первый',
  'Тайный',
  'Секретный',
  'Скрытый',
  'Забытый',
  'Утерянный',
  'Потерянный',
  'Найденный',
  'Темный',
  'Светлый',
  'Красный',
  'Черный',
  'Белый',
  'Золотой',
  'Серебряный',
  'Ночной',
  'Дневной',
  'Вечный',
  'Бесконечный',
  'Проклятый',
  'Благословенный',
  'Священный',
  'Запретный',
  'Странный',
  'Великий',
  'Малый',
  'Древний',
  'Новый',
  'Старый',
  'Юный',
  'Мертвый',
  'Живой',
  'Падший',
  'Восставший',
  'Спящий',
  'Проснувшийся',
  'Далекий',
  'Близкий',
  'Северный',
  'Южный',
  'Восточный',
  'Западный',
  'Небесный',
  'Подземный',
  'Морской',
  'Горный',
  'Лесной',
  'Пустынный',
  'Ледяной',
];

const List<String> suffixWords = [
  'Хроники',
  'Легенда',
  'Сага',
  'История',
  'Рассказ',
  'Повесть',
  'Роман',
  'Дневник',
  'Записки',
  'Воспоминания',
  'Тайна',
  'Секрет',
  'Загадка',
  'Мистерия',
  'Приключения',
  'Путешествие',
  'Поиск',
  'Квест',
  'Охота',
  'Битва',
  'Война',
  'Мир',
  'Империя',
  'Королевство',
  'Трон',
  'Корона',
  'Меч',
  'Щит',
  'Кольцо',
  'Амулет',
  'Талисман',
  'Артефакт',
  'Реликвия',
  'Сокровище',
  'Клад',
  'Книга',
  'Том',
  'Манускрипт',
  'Свиток',
  'Кодекс',
  'Заклинание',
  'Пророчество',
  'Предсказание',
  'Судьба',
  'Проклятие',
  'Благословение',
  'Дар',
  'Наследие',
  'Завет',
  'Обет',
  'Клятва',
  'Договор',
  'Пакт',
  'Союз',
  'Братство',
  'Орден',
  'Гильдия',
  'Клан',
  'Семья',
  'Династия',
  'Род',
  'Наследник',
  'Преемник',
  'Избранный',
  'Герой',
  'Злодей',
  'Маг',
  'Колдун',
  'Волшебник',
  'Ведьма',
  'Дракон',
  'Феникс',
  'Грифон',
  'Единорог',
  'Кентавр',
  'Эльф',
  'Гном',
  'Орк',
  'Демон',
  'Ангел',
  'Бог',
  'Титан',
  'Гигант',
  'Призрак',
  'Дух',
  'Тень',
  'Фантом',
  'Видение',
  'Сон',
  'Кошмар',
  'Иллюзия',
  'Реальность',
  'Измерение',
  'Портал',
  'Врата',
  'Дверь',
  'Путь',
  'Дорога',
];

const List<String> genres = [
  'Фэнтези',
  'Научная фантастика',
  'Детектив',
  'Триллер',
  'Романы',
  'Историческая проза',
  'Биография',
  'Мемуары',
  'Поэзия',
  'Философия',
  'Драма',
  'Комедия',
  'Приключения',
  'Ужасы',
  'Мистика',
  'Фантастика',
  'Киберпанк',
  'Стимпанк',
  'Постапокалипсис',
  'Антиутопия',
  'Бизнес',
  'Для детей',
  'Детективы и триллеры',
  'Для души и тела',
  'Здоровье и спорт',
  'История',
  'Компьютеры и технологии',
  'Кулинария и домашнее хозяйство',
  'Любовные романы',
  'Саморазвитие',
  'Художественная литература',
];

const Map<String, String> genresEnByRu = {
  'Фэнтези': 'Fantasy',
  'Научная фантастика': 'Science fiction',
  'Детектив': 'Detective',
  'Триллер': 'Thriller',
  'Романы': 'Novels',
  'Историческая проза': 'Historical fiction',
  'Биография': 'Biography',
  'Мемуары': 'Memoirs',
  'Поэзия': 'Poetry',
  'Философия': 'Philosophy',
  'Драма': 'Drama',
  'Комедия': 'Comedy',
  'Приключения': 'Adventures',
  'Ужасы': 'Horror',
  'Мистика': 'Mysticism',
  'Фантастика': 'Speculative fiction',
  'Киберпанк': 'Cyberpunk',
  'Стимпанк': 'Steampunk',
  'Постапокалипсис': 'Post-apocalyptic',
  'Антиутопия': 'Dystopia',
  'Бизнес': 'Business',
  'Для детей': 'For children',
  'Детективы и триллеры': 'Crime & thrillers',
  'Для души и тела': 'For mind and body',
  'Здоровье и спорт': 'Health & sport',
  'История': 'History',
  'Компьютеры и технологии': 'Computers & technology',
  'Кулинария и домашнее хозяйство': 'Cooking & home',
  'Любовные романы': 'Romance',
  'Саморазвитие': 'Self-improvement',
  'Художественная литература': 'Fiction',
};

const List<String> bookTags = [
  'Бестселлер',
  'Классика',
  'Современная литература',
  'Экранизация',
  'Серия',
  'Молодежная литература',
  'Детская литература',
  'Антиутопия',
  'Мистика',
  'Детектив',
  'Психологический триллер',
  'Эпическое фэнтези',
  'Городское фэнтези',
  'Темное фэнтези',
  'Космическая опера',
  'Твердая НФ',
  'Альтернативная история',
  'Магический реализм',
  'Нуар',
  'Шпионский роман',
  'Любовный роман',
  'Исторический роман',
  'Военная проза',
  'Приключенческая проза',
  'Сатира',
  'Пародия',
  'Готика',
  'Хоррор',
  'Философская проза',
  'Постмодернизм',
  'Реализм',
  'Сюрреализм',
  'Абсурдизм',
  'Экзистенциализм',
  'Дзен',
  'Буддизм',
  'Христианство',
  'Самопознание',
  'Саморазвитие',
  'Мотивация',
  'Успех',
  'Новинка',
  'Самоучитель',
];

const Map<String, String> bookTagsEnByRu = {
  'Бестселлер': 'Bestseller',
  'Классика': 'Classics',
  'Современная литература': 'Contemporary literature',
  'Экранизация': 'Adaptations',
  'Серия': 'Series',
  'Молодежная литература': 'Young adult literature',
  'Детская литература': "Children's literature",
  'Антиутопия': 'Dystopia',
  'Мистика': 'Mysticism',
  'Детектив': 'Detective',
  'Психологический триллер': 'Psychological thriller',
  'Эпическое фэнтези': 'Epic fantasy',
  'Городское фэнтези': 'Urban fantasy',
  'Темное фэнтези': 'Dark fantasy',
  'Космическая опера': 'Space opera',
  'Твердая НФ': 'Hard SF',
  'Альтернативная история': 'Alternative history',
  'Магический реализм': 'Magical realism',
  'Нуар': 'Noir',
  'Шпионский роман': 'Spy novel',
  'Любовный роман': 'Love story',
  'Исторический роман': 'Historical novel',
  'Военная проза': 'War prose',
  'Приключенческая проза': 'Adventure prose',
  'Сатира': 'Satire',
  'Пародия': 'Parody',
  'Готика': 'Gothic',
  'Хоррор': 'Horror',
  'Философская проза': 'Philosophical prose',
  'Постмодернизм': 'Postmodernism',
  'Реализм': 'Realism',
  'Сюрреализм': 'Surrealism',
  'Абсурдизм': 'Absurdism',
  'Экзистенциализм': 'Existentialism',
  'Дзен': 'Zen',
  'Буддизм': 'Buddhism',
  'Христианство': 'Christianity',
  'Самопознание': 'Self-discovery',
  'Саморазвитие': 'Self-development',
  'Мотивация': 'Motivation',
  'Успех': 'Success',
  'Новинка': 'New release',
  'Самоучитель': 'Self-study',
};

const List<String> icons = [
  'assets/icons/books_icons/1984.webp',
  'assets/icons/books_icons/alice_in_wonderland.webp',
  'assets/icons/books_icons/animal_farm.webp',
  'assets/icons/books_icons/an_american_tragedy_1.webp',
  'assets/icons/books_icons/a_clash_of_kings.webp',
  'assets/icons/books_icons/a_game_of_thrones.webp',
  'assets/icons/books_icons/betrayal.webp',
  'assets/icons/books_icons/big_swiss.webp',
  'assets/icons/books_icons/cause_to_dread.webp',
  'assets/icons/books_icons/dandelion_wine.webp',
  'assets/icons/books_icons/drive.webp',
  'assets/icons/books_icons/foresight.webp',
  'assets/icons/books_icons/foundation_and_empire.webp',
  'assets/icons/books_icons/girl_in_the_yellow_coat.webp',
  'assets/icons/books_icons/hotel.webp',
  'assets/icons/books_icons/if_tomorrow_comes.webp',
  'assets/icons/books_icons/inside_the_killer.webp',
  'assets/icons/books_icons/jump.webp',
  'assets/icons/books_icons/lemons_lemons_lemons_lemons_lemons.webp',
  'assets/icons/books_icons/little_women.webp',
  'assets/icons/books_icons/love_with_death.webp',
  'assets/icons/books_icons/metamorphosis.webp',
  'assets/icons/books_icons/moby_dick.webp',
  'assets/icons/books_icons/never_let_me_go.webp',
  'assets/icons/books_icons/normal_people.webp',
  'assets/icons/books_icons/only_forward.webp',
  'assets/icons/books_icons/on_leadership.webp',
  'assets/icons/books_icons/past.webp',
  'assets/icons/books_icons/piecelove.webp',
  'assets/icons/books_icons/pride_and_prejudice.webp',
  'assets/icons/books_icons/small_things_like_these.webp',
  'assets/icons/books_icons/tender_is_the_night.webp',
  'assets/icons/books_icons/the_ashes_of_london.webp',
  'assets/icons/books_icons/the_a_b_c_murders.webp',
  'assets/icons/books_icons/the_court_of_icy_hearts.webp',
  'assets/icons/books_icons/the_covenant_of_water.webp',
  'assets/icons/books_icons/the_devil_wears_prada.webp',
  'assets/icons/books_icons/the_dice_man.webp',
  'assets/icons/books_icons/the_flaw.webp',
  'assets/icons/books_icons/the_grinch.webp',
  'assets/icons/books_icons/the_hobbit.webp',
  'assets/icons/books_icons/the_hunting_party.webp',
  'assets/icons/books_icons/the_imperial_guardian.webp',
  'assets/icons/books_icons/the_it.webp',
  'assets/icons/books_icons/the_limit.webp',
  'assets/icons/books_icons/the_lord_of_the_ring.webp',
  'assets/icons/books_icons/the_pioneers.webp',
  'assets/icons/books_icons/the_starry_messenger.webp',
  'assets/icons/books_icons/the_weight_of_honor.webp',
  'assets/icons/books_icons/three_days_of_indigo.webp',
  'assets/icons/books_icons/three_men_in_a_boat.webp',
  'assets/icons/books_icons/through_another_night.webp',
  'assets/icons/books_icons/utopia.webp',
  'assets/icons/books_icons/vassal_state.webp',
  'assets/icons/books_icons/wealth_of_wisdom.webp',
  'assets/icons/books_icons/world_of_warcraft.webp',
];

const List<String> publishers = [
  'АСТ',
  'Эксмо',
  'Азбука',
  'Азбука-Аттикус',
  'Росмэн',
  'Манн, Иванов и Фербер',
  'Альпина Паблишер',
  'Питер',
  'Просвещение',
  'Дрофа',
  'Вентана-Граф',
  'Махаон',
  'Clever',
  'Самокат',
  'КомпасГид',
  'Фантом Пресс',
  'Абрис',
  'Livebook',
  'Рипол Классик',
  'Добрая книга',
];

const List<String> awards = [
  'Букер',
  'Национальный бестселлер',
  'Русский Букер',
  'Большая книга',
  'Ясная Поляна',
  'НОС',
  'Дебют',
  'Студенческий Букер',
  'Премия Андрея Белого',
  'Премия имени Аркадия и Бориса Стругацких',
  'Портал',
  'Звездный мост',
  'Интерпресскон',
  'Награда Всемирного фэнтези',
  'Хьюго',
  'Небьюла',
  'Локус',
  'Премия Артура Кларка',
  'Премия Филипа К. Дика',
  'Британская премия фэнтези',
];

const List<String> narrators = [
  'Алексей Иванов',
  'Мария Петрова',
  'Дмитрий Сидоров',
  'Елена Соколова',
  'Николай Васильев',
  'Ольга Смирнова',
  'Андрей Кузнецов',
  'Татьяна Новикова',
  'Сергей Морозов',
  'Анна Федорова',
  'Владимир Попов',
  'Наталья Волкова',
  'Михаил Лебедев',
  'Ирина Козлова',
  'Павел Орлов',
];

const List<String> seriesNames = [
  'Хроники Тьмы',
  'Саги Севера',
  'Легенды Востока',
  'Записки путешественника',
  'Детективы большого города',
  'Мистерии ночи',
  'Космические приключения',
  'Магическая академия',
  'Королевская сага',
  'Империя магов',
  'Тайны прошлого',
  'Война миров',
  'Забытые королевства',
  'Звездные войны',
  'Академия убийц',
  'Дети богов',
  'Проклятие династии',
  'Секреты древних',
  'Последние герои',
  'Врата времени',
];

const List<String> languages = [
  'Čeština',
  'Dansk',
  'Deutsch',
  'English',
  'Español',
  'Français',
  'Indonesia',
  'Italiano',
  'Magyar',
  'Melayu',
  'Nederlands',
  'Norsk bokmål',
  'Polski',
  'Português',
  'Română',
  'Slovenčina',
  'Suomi',
  'Svenska',
  'Tiếng Việt',
  'Türkçe',
  'Ελληνικά',
  'Русский',
  'українська',
  'עברית',
  'العربية',
  'मराठी',
  'हिंदी',
  'বাংলা',
  'தமிழ்',
  'ไทย',
  '한국어',
  '日本語',
  '中文',
];

const List<String> formats = ['ePub', 'Audiobook'];
