// GENERATED CODE - DO NOT MODIFY BY HAND

part of '../product_models/book_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Book _$BookFromJson(Map<String, dynamic> json) => Book(
  type: json['type'] as String,
  id: json['id'] as String,
  title: json['title'] as String,
  creator: json['creator'] as String,
  rating: (json['rating'] as num).toDouble(),
  shortDescription: json['shortDescription'] as String,
  iconUrl: json['iconUrl'] as String,
  isPaid: json['isPaid'] as bool,
  publisher: json['publisher'] as String,
  isbn: json['isbn'] as String,
  pageCount: (json['pageCount'] as num).toInt(),
  language: json['language'] as String,
  format: json['format'] as String,
  publicationDate: DateTime.parse(json['publicationDate'] as String),
  description: json['description'] as String,
  genres: (json['genres'] as List<dynamic>).map((e) => e as String).toList(),
  tags: (json['tags'] as List<dynamic>).map((e) => e as String).toList(),
  hasAudioVersion: json['hasAudioVersion'] as bool,
  audioDuration: (json['audioDuration'] as num?)?.toInt(),
  narrator: json['narrator'] as String?,
  isSeries: json['isSeries'] as bool,
  seriesName: json['seriesName'] as String?,
  seriesNumber: (json['seriesNumber'] as num?)?.toInt(),
  sampleAvailable: json['sampleAvailable'] as bool,
  isAbridged: json['isAbridged'] as bool,
  price: (json['price'] as num?)?.toDouble(),
  awards: (json['awards'] as List<dynamic>).map((e) => e as String).toList(),
  releaseDate: DateTime.parse(json['releaseDate'] as String),
  reviewsCount: (json['reviewsCount'] as num).toInt(),
  creatorDescription: json['creatorDescription'] as String,
  url: json['url'] as String,
);

Map<String, dynamic> _$BookToJson(Book instance) => <String, dynamic>{
  'type': instance.type,
  'id': instance.id,
  'title': instance.title,
  'creator': instance.creator,
  'shortDescription': instance.shortDescription,
  'description': instance.description,
  'rating': instance.rating,
  'reviewsCount': instance.reviewsCount,
  'releaseDate': instance.releaseDate.toIso8601String(),
  'creatorDescription': instance.creatorDescription,
  'iconUrl': instance.iconUrl,
  'isPaid': instance.isPaid,
  'price': instance.price,
  'publisher': instance.publisher,
  'isbn': instance.isbn,
  'pageCount': instance.pageCount,
  'language': instance.language,
  'format': instance.format,
  'publicationDate': instance.publicationDate.toIso8601String(),
  'genres': instance.genres,
  'tags': instance.tags,
  'hasAudioVersion': instance.hasAudioVersion,
  'audioDuration': instance.audioDuration,
  'narrator': instance.narrator,
  'isSeries': instance.isSeries,
  'seriesName': instance.seriesName,
  'seriesNumber': instance.seriesNumber,
  'sampleAvailable': instance.sampleAvailable,
  'isAbridged': instance.isAbridged,
  'awards': instance.awards,
  'url': instance.url,
};
