// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDIx7wo1vo3US4AxETICwj3REZlO_Zg7Lo',
//     appId: '1:143688114166:web:816c7406b95d1fb453b1d7',
//     messagingSenderId: '143688114166',
//     projectId: 'play-clone-96136',
//     authDomain: 'play-clone-96136.firebaseapp.com',
//     storageBucket: 'play-clone-96136.firebasestorage.app',
//     measurementId: 'G-419KQ5T3YX',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDu2fwqexgN8KeGCHeToCRIJokreiZB4go',
//     appId: '1:143688114166:android:029988938c9ba46c53b1d7',
//     messagingSenderId: '143688114166',
//     projectId: 'play-clone-96136',
//     storageBucket: 'play-clone-96136.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCbCOm_c78QpTct1hn-0swpbV6NxpGtkBA',
//     appId: '1:143688114166:ios:b2d91c546a0f944753b1d7',
//     messagingSenderId: '143688114166',
//     projectId: 'play-clone-96136',
//     storageBucket: 'play-clone-96136.firebasestorage.app',
//     iosBundleId: 'com.example.googlePlay',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCbCOm_c78QpTct1hn-0swpbV6NxpGtkBA',
//     appId: '1:143688114166:ios:b2d91c546a0f944753b1d7',
//     messagingSenderId: '143688114166',
//     projectId: 'play-clone-96136',
//     storageBucket: 'play-clone-96136.firebasestorage.app',
//     iosBundleId: 'com.example.googlePlay',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDIx7wo1vo3US4AxETICwj3REZlO_Zg7Lo',
//     appId: '1:143688114166:web:39c6bef60b8f818353b1d7',
//     messagingSenderId: '143688114166',
//     projectId: 'play-clone-96136',
//     authDomain: 'play-clone-96136.firebaseapp.com',
//     storageBucket: 'play-clone-96136.firebasestorage.app',
//     measurementId: 'G-WC11CVDCJT',
//   );
// }
