const List<String> prefixWords = [
  'Smart',
  'Quick',
  'Easy',
  'Pro',
  'Plus',
  'Master',
  'Super',
  'Mega',
  'Ultra',
  'Prime',
  'Cloud',
  'Digital',
  'My',
  'Social',
  'Best',
  'Top',
  'Fast',
  'Secure',
  'Safe',
  'Power',
  'Boost',
  'Max',
  'Elite',
  'Premium',
  'Daily',
  'Instant',
  'Auto',
  'Simple',
  'Perfect',
  'Pure',
  'Bright',
  'Smart',
  'Next',
  'Future',
  'Modern',
  'Advanced',
  'Expert',
  'Universal',
  'Global',
  'Local',
  'Personal',
  'Private',
  'Express',
  'Direct',
  'True',
  'Real',
  'Active',
  'Live',
  'Dynamic',
  'Flex',
];

const List<String> suffixWords = [
  'Chat',
  'Talk',
  'Connect',
  'Link',
  'Share',
  'Post',
  'Feed',
  'Stream',
  'Play',
  'Music',
  'Video',
  'Photo',
  'Pic',
  'Snap',
  'Edit',
  'Studio',
  'Creator',
  'Maker',
  'Builder',
  'Manager',
  'Tracker',
  'Monitor',
  'Scanner',
  'Reader',
  'Viewer',
  'Player',
  'Browser',
  'Explorer',
  'Finder',
  'Search',
  'Shop',
  'Store',
  'Market',
  'Cart',
  'Pay',
  'Wallet',
  'Bank',
  'Money',
  'Budget',
  'Finance',
  'Health',
  'Fitness',
  'Diet',
  'Workout',
  'Coach',
  'Guide',
  'Learn',
  'Teach',
  'Study',
  'Book',
  'Note',
  'Task',
  'Planner',
  'Organizer',
  'Calendar',
  'Reminder',
  'Timer',
  'Clock',
  'Weather',
  'News',
  'Map',
  'Travel',
  'Trip',
  'Hotel',
  'Flight',
  'Food',
  'Recipe',
  'Cook',
  'Delivery',
  'Ride',
  'Drive',
  'Parking',
];

const List<String> appTags = [
  'Облачное хранилище',
  'Видеозвонки',
  'Редактор фото',
  'Доставка еды',
  'Стриминг',
  'Офлайн режим',
  'Синхронизация',
  'Уведомления в реальном времени',
  'Мессенджер',
  'Социальная сеть',
  'Фильтры',
  'Коллажи',
  'Анимация',
  'Музыка',
  'Подкасты',
  'Видеоредактор',
  'Шопинг',
  'Скидки',
  'Доставка',
  'Отслеживание заказов',
  'Онлайн-оплата',
  'Безопасность',
  'Шифрование',
  'Конфиденциальность',
  'Резервное копирование',
  'Виджеты',
  'Темная тема',
  'Персонализация',
  'Мультиязычность',
  'GPS',
  'Карты',
  'Навигация',
  'AR технологии',
  'Сканер QR',
  'Календарь',
  'Напоминания',
  'Заметки',
  'Списки дел',
  'Продуктивность',
  'Тайм-менеджмент',
  'Работа',
  'Списки',
  'Утилиты',
  'Развлечения',
];

const Map<String, String> appTagsEnByRu = {
  'Облачное хранилище': 'Cloud storage',
  'Видеозвонки': 'Video calls',
  'Редактор фото': 'Photo editor',
  'Доставка еды': 'Food delivery',
  'Стриминг': 'Streaming',
  'Офлайн режим': 'Offline mode',
  'Синхронизация': 'Sync',
  'Уведомления в реальном времени': 'Real-time notifications',
  'Мессенджер': 'Messenger',
  'Социальная сеть': 'Social network',
  'Фильтры': 'Filters',
  'Коллажи': 'Collages',
  'Анимация': 'Animation',
  'Музыка': 'Music',
  'Подкасты': 'Podcasts',
  'Видеоредактор': 'Video editor',
  'Шопинг': 'Shopping',
  'Скидки': 'Discounts',
  'Доставка': 'Delivery',
  'Отслеживание заказов': 'Order tracking',
  'Онлайн-оплата': 'Online payments',
  'Безопасность': 'Security',
  'Шифрование': 'Encryption',
  'Конфиденциальность': 'Privacy',
  'Резервное копирование': 'Backup',
  'Виджеты': 'Widgets',
  'Темная тема': 'Dark theme',
  'Персонализация': 'Personalization',
  'Мультиязычность': 'Multilingual',
  'GPS': 'GPS',
  'Карты': 'Maps',
  'Навигация': 'Navigation',
  'AR технологии': 'AR technologies',
  'Сканер QR': 'QR scanner',
  'Календарь': 'Calendar',
  'Напоминания': 'Reminders',
  'Заметки': 'Notes',
  'Списки дел': 'To-do lists',
  'Продуктивность': 'Productivity',
  'Тайм-менеджмент': 'Time management',
  'Работа': 'Work',
  'Списки': 'Lists',
  'Утилиты': 'Utilities',
  'Развлечения': 'Entertainment',
};

const List<String> icons = [
  'assets/icons/apps_icons/aliexpress.webp',
  'assets/icons/apps_icons/amazon_shopping.webp',
  'assets/icons/apps_icons/best_buy.webp',
  'assets/icons/apps_icons/burger_king.webp',
  'assets/icons/apps_icons/canva.webp',
  'assets/icons/apps_icons/capcut.webp',
  'assets/icons/apps_icons/chatgpt.webp',
  'assets/icons/apps_icons/cookpad.webp',
  'assets/icons/apps_icons/crumbl.webp',
  'assets/icons/apps_icons/crunchyroll.webp',
  'assets/icons/apps_icons/dick_s_sportimg_goods.webp',
  'assets/icons/apps_icons/discord.webp',
  'assets/icons/apps_icons/disney.webp',
  'assets/icons/apps_icons/duolingowebp.webp',
  'assets/icons/apps_icons/ebay.webp',
  'assets/icons/apps_icons/etsy.webp',
  'assets/icons/apps_icons/facebook.webp',
  'assets/icons/apps_icons/firefox.webp',
  'assets/icons/apps_icons/gap.webp',
  'assets/icons/apps_icons/google_chrome.webp',
  'assets/icons/apps_icons/google_gemini.webp',
  'assets/icons/apps_icons/grok.webp',
  'assets/icons/apps_icons/hbo_max.webp',
  'assets/icons/apps_icons/hulu.webp',
  'assets/icons/apps_icons/ikea.webp',
  'assets/icons/apps_icons/instagram.webp',
  'assets/icons/apps_icons/joom.webp',
  'assets/icons/apps_icons/kfc.webp',
  'assets/icons/apps_icons/krita.webp',
  'assets/icons/apps_icons/lightroom_photo.webp',
  'assets/icons/apps_icons/likee.webp',
  'assets/icons/apps_icons/locket_widget.webp',
  'assets/icons/apps_icons/mcdonald_s.webp',
  'assets/icons/apps_icons/microsoft_edge.webp',
  'assets/icons/apps_icons/microsoft_powerpoint.webp',
  'assets/icons/apps_icons/miro.webp',
  'assets/icons/apps_icons/netflix.webp',
  'assets/icons/apps_icons/nike.webp',
  'assets/icons/apps_icons/opera.webp',
  'assets/icons/apps_icons/paramount.webp',
  'assets/icons/apps_icons/paypal.webp',
  'assets/icons/apps_icons/photoshop.webp',
  'assets/icons/apps_icons/picsart.webp',
  'assets/icons/apps_icons/pinterest.webp',
  'assets/icons/apps_icons/pizza_hut.webp',
  'assets/icons/apps_icons/sephora.webp',
  'assets/icons/apps_icons/shein.webp',
  'assets/icons/apps_icons/sketchbook.webp',
  'assets/icons/apps_icons/smule.webp',
  'assets/icons/apps_icons/snapchat.webp',
  'assets/icons/apps_icons/spotify.webp',
  'assets/icons/apps_icons/taco_bell_fast_food.webp',
  'assets/icons/apps_icons/target.webp',
  'assets/icons/apps_icons/telegram.webp',
  'assets/icons/apps_icons/temu.webp',
  'assets/icons/apps_icons/threads.webp',
  'assets/icons/apps_icons/tiktok.webp',
  'assets/icons/apps_icons/uber.webp',
  'assets/icons/apps_icons/uber_eats.webp',
  'assets/icons/apps_icons/venmo.webp',
  'assets/icons/apps_icons/viber.webp',
  'assets/icons/apps_icons/walmart.webp',
  'assets/icons/apps_icons/wattpad.webp',
  'assets/icons/apps_icons/wechat.webp',
  'assets/icons/apps_icons/wendy_s.webp',
  'assets/icons/apps_icons/whatsapp_messenger.webp',
  'assets/icons/apps_icons/widgetable.webp',
  'assets/icons/apps_icons/wikipedia.webp',
  'assets/icons/apps_icons/xbox.webp',
  'assets/icons/apps_icons/yahoo_mail.webp',
  'assets/icons/apps_icons/youtube.webp',
  'assets/icons/apps_icons/zip.webp',
];

const List<String> screenshots = [
  'assets/images/apps_screenshots/aliexpress_vert_1.webp',
  'assets/images/apps_screenshots/aliexpress_vert_2.webp',
  'assets/images/apps_screenshots/aliexpress_vert_3.webp',
  'assets/images/apps_screenshots/aliexpress_vert_4.webp',
  'assets/images/apps_screenshots/aliexpress_vert_5.webp',
  'assets/images/apps_screenshots/aliexpress_vert_6.webp',
  'assets/images/apps_screenshots/crumbl_vert_1.webp',
  'assets/images/apps_screenshots/crumbl_vert_2.webp',
  'assets/images/apps_screenshots/crumbl_vert_3.webp',
  'assets/images/apps_screenshots/crumbl_vert_4.webp',
  'assets/images/apps_screenshots/crumbl_vert_5.webp',
  'assets/images/apps_screenshots/crumbl_vert_6.webp',
  'assets/images/apps_screenshots/crumbl_vert_7.webp',
  'assets/images/apps_screenshots/discord_vert_1.webp',
  'assets/images/apps_screenshots/discord_vert_2.webp',
  'assets/images/apps_screenshots/discord_vert_3.webp',
  'assets/images/apps_screenshots/discord_vert_4.webp',
  'assets/images/apps_screenshots/discord_vert_5.webp',
  'assets/images/apps_screenshots/duolingo_vert_1.webp',
  'assets/images/apps_screenshots/duolingo_vert_2.webp',
  'assets/images/apps_screenshots/duolingo_vert_3.webp',
  'assets/images/apps_screenshots/duolingo_vert_4.webp',
  'assets/images/apps_screenshots/duolingo_vert_5.webp',
  'assets/images/apps_screenshots/duolingo_vert_6.webp',
  'assets/images/apps_screenshots/duolingo_vert_7.webp',
  'assets/images/apps_screenshots/ebay_vert_1.webp',
  'assets/images/apps_screenshots/ebay_vert_2.webp',
  'assets/images/apps_screenshots/ebay_vert_3.webp',
  'assets/images/apps_screenshots/ebay_vert_4.webp',
  'assets/images/apps_screenshots/ebay_vert_5.webp',
  'assets/images/apps_screenshots/ebay_vert_6.webp',
  'assets/images/apps_screenshots/etsy_vert_1.webp',
  'assets/images/apps_screenshots/etsy_vert_2.webp',
  'assets/images/apps_screenshots/etsy_vert_3.webp',
  'assets/images/apps_screenshots/etsy_vert_4.webp',
  'assets/images/apps_screenshots/etsy_vert_5.webp',
  'assets/images/apps_screenshots/etsy_vert_6.webp',
  'assets/images/apps_screenshots/google_chrome_vert_1.webp',
  'assets/images/apps_screenshots/google_chrome_vert_2.webp',
  'assets/images/apps_screenshots/google_chrome_vert_3.webp',
  'assets/images/apps_screenshots/google_chrome_vert_4.webp',
  'assets/images/apps_screenshots/google_chrome_vert_5.webp',
  'assets/images/apps_screenshots/miro_vert_1.webp',
  'assets/images/apps_screenshots/miro_vert_2.webp',
  'assets/images/apps_screenshots/miro_vert_3.webp',
  'assets/images/apps_screenshots/miro_vert_4.webp',
  'assets/images/apps_screenshots/miro_vert_5.webp',
  'assets/images/apps_screenshots/pintererst_vert_1.webp',
  'assets/images/apps_screenshots/pintererst_vert_2.webp',
  'assets/images/apps_screenshots/pintererst_vert_3.webp',
  'assets/images/apps_screenshots/pintererst_vert_4.webp',
  'assets/images/apps_screenshots/pintererst_vert_5.webp',
  'assets/images/apps_screenshots/pizza_hut_vert_1.webp',
  'assets/images/apps_screenshots/pizza_hut_vert_2.webp',
  'assets/images/apps_screenshots/pizza_hut_vert_3.webp',
  'assets/images/apps_screenshots/pizza_hut_vert_4.webp',
  'assets/images/apps_screenshots/pizza_hut_vert_5.webp',
  'assets/images/apps_screenshots/tik_tok_vert_1.webp',
  'assets/images/apps_screenshots/tik_tok_vert_2.webp',
  'assets/images/apps_screenshots/tik_tok_vert_3.webp',
  'assets/images/apps_screenshots/tik_tok_vert_4.webp',
  'assets/images/apps_screenshots/tik_tok_vert_5.webp',
  'assets/images/apps_screenshots/whatsapp_vert1.webp',
  'assets/images/apps_screenshots/whatsapp_vert2.webp',
  'assets/images/apps_screenshots/whatsapp_vert3.webp',
  'assets/images/apps_screenshots/whatsapp_vert4.webp',
  'assets/images/apps_screenshots/whatsapp_vert5.webp',
  'assets/images/apps_screenshots/zoom_workplace_horiz_1.webp',
  'assets/images/apps_screenshots/zoom_workplace_horiz_2.webp',
  'assets/images/apps_screenshots/zoom_workplace_horiz_3.webp',
  'assets/images/apps_screenshots/zoom_workplace_vert_1.webp',
  'assets/images/apps_screenshots/zoom_workplace_vert_2.webp',
  'assets/images/apps_screenshots/zoom_workplace_vert_3.webp',
  'assets/images/apps_screenshots/zoom_workplace_vert_4.webp',
  'assets/images/apps_screenshots/zoom_workplace_vert_5.webp',
  'assets/images/apps_screenshots/zoom_workplace_vert_6.webp',
];

const List<int> ageRatings = [3, 5, 6, 8, 9, 12, 16, 18];

const List<String> permissions = [
  'Камера',
  'Микрофон',
  'Геолокация',
  'Контакты',
  'Хранилище',
  'Уведомления',
  'Календарь',
  'Фото',
  'Видео',
  'Bluetooth',
  'Информация о Wi-Fi подключении',
  'Идентификатор устройства и данные о вызовах',
  'Неограниченный доступ к Интернету',
  'Просмотр сетевых подключений',
  'Запуск при включении устройства',
  'Предотвращение спящего режима',
  'Управление вибросигналом',
  'Изменение настроек системы',
  'Точное местоположение (на основе сети и сигналов GPS)',
  'Приблизительное местоположение (на основе сети)',
  'Чтение журнала вызовов',
  'Чтение SMS',
  'Отправка SMS',
  'Чтение содержимого USB-накопителя',
  'Изменение или удаление содержимого USB-накопителя',
  'Поиск аккаунтов на устройстве',
  'NFC-модуль',
  'Нательные датчики',
  'Получение данных из Интернета',
  'Play Install Referrer API',
  'Запуск фоновых служб',
  'Разрешение на рекламный идентификатор',
  'Доступ к списку установленных приложений',
  'Доступ к биометрическим данным',
  'Статистика использования',
  'Наложение поверх других окон',
  'Доступ к медиафайлам',
  'Чтение истории браузера',
  'Установка пакетов приложений',
  'Доступ к списку вызовов',
  'Доступ к буферу обмена',
];

const Map<String, String> permissionsEnByRu = {
  'Камера': 'Camera',
  'Микрофон': 'Microphone',
  'Геолокация': 'Location',
  'Контакты': 'Contacts',
  'Хранилище': 'Storage',
  'Уведомления': 'Notifications',
  'Календарь': 'Calendar',
  'Фото': 'Photos',
  'Видео': 'Video',
  'Bluetooth': 'Bluetooth',
  'Информация о Wi-Fi подключении': 'Wi-Fi connection information',
  'Идентификатор устройства и данные о вызовах': 'Device ID and call data',
  'Неограниченный доступ к Интернету': 'Full internet access',
  'Просмотр сетевых подключений': 'View network connections',
  'Запуск при включении устройства': 'Start at device boot',
  'Предотвращение спящего режима': 'Prevent sleep',
  'Управление вибросигналом': 'Control vibration',
  'Изменение настроек системы': 'Modify system settings',
  'Точное местоположение (на основе сети и сигналов GPS)':
      'Precise location (network and GPS signals)',
  'Приблизительное местоположение (на основе сети)':
      'Approximate location (network-based)',
  'Чтение журнала вызовов': 'Read call log',
  'Чтение SMS': 'Read SMS',
  'Отправка SMS': 'Send SMS',
  'Чтение содержимого USB-накопителя': 'Read USB storage contents',
  'Изменение или удаление содержимого USB-накопителя':
      'Modify or delete USB storage contents',
  'Поиск аккаунтов на устройстве': 'Find accounts on device',
  'NFC-модуль': 'NFC module',
  'Нательные датчики': 'Body sensors',
  'Получение данных из Интернета': 'Retrieve data from the internet',
  'Play Install Referrer API': 'Play Install Referrer API',
  'Запуск фоновых служб': 'Run background services',
  'Разрешение на рекламный идентификатор':
      'Permission to the advertising identifier',
  'Доступ к списку установленных приложений':
      'Access to the list of installed apps',
  'Доступ к биометрическим данным': 'Access to biometric data',
  'Статистика использования': 'Usage statistics',
  'Наложение поверх других окон': 'Appear on top of other apps',
  'Доступ к медиафайлам': 'Access to media files',
  'Чтение истории браузера': 'Read browser history',
  'Установка пакетов приложений': 'Install app packages',
  'Доступ к списку вызовов': 'Access to call list',
  'Доступ к буферу обмена': 'Access clipboard',
};

const List<String> languages = [
  'RU',
  'EN',
  'ES',
  'FR',
  'DE',
  'IT',
  'PT',
  'ZH',
  'JA',
  'KO',
];

const List<String> ageRatingReasons = [
  'Насилие',
  'Страх',
  'Сцены сексуального характера',
  'Наркотики',
  'Сквернословие',
  'Азартные игры',
  'Дискриминация',
  'Внутриигровые покупки',
  'Взаимодействие пользователей',
];

const Map<String, String> ageRatingReasonsEnByRu = {
  'Насилие': 'Violence',
  'Страх': 'Fear',
  'Сцены сексуального характера': 'Sexual content',
  'Наркотики': 'Drugs',
  'Сквернословие': 'Profanity',
  'Азартные игры': 'Gambling',
  'Дискриминация': 'Discrimination',
  'Внутриигровые покупки': 'In-app purchases',
  'Взаимодействие пользователей': 'User interaction',
};

const List<String> appCategories = [
  'Автомобили и транспорт',
  'Бизнес',
  'Виеоплееры и редакторы',
  'Детям',
  'Еда и напитки',
  'Жилье и дом',
  'Здоровье и фитнес',
  'Знакомства',
  'Игры',
  'Инструменты',
  'Исскуство и дизайн',
  'Карты и навигации',
  'Книги и справочники',
  'Комиксы',
  'Красота',
  'Материнство и детство',
  'Медицина',
  'Мероприятия',
  'Музыка и аудио',
  'Новости и журналы',
  'Образование',
  'Персонализация',
  'Погода',
  'Покупки',
  'Приложения для часов',
  'Путешествия',
  'Работа',
  'Развлечения',
  'Разное',
  'Связь',
  'Социальные',
  'Спорт',
  'Стиль жизни',
  'Финансы',
  'Фотография',
  'Циферблаты',
];

const Map<String, String> appCategoriesEnByRu = {
  'Автомобили и транспорт': 'Auto & Transportation',
  'Бизнес': 'Business',
  'Виеоплееры и редакторы': 'Video Players & Editors',
  'Детям': 'For Kids',
  'Еда и напитки': 'Food & Drink',
  'Жилье и дом': 'House & Home',
  'Здоровье и фитнес': 'Health & Fitness',
  'Знакомства': 'Dating',
  'Игры': 'Games',
  'Инструменты': 'Tools',
  'Исскуство и дизайн': 'Art & Design',
  'Карты и навигации': 'Maps & Navigation',
  'Книги и справочники': 'Books & Reference',
  'Комиксы': 'Comics',
  'Красота': 'Beauty',
  'Материнство и детство': 'Parenting',
  'Медицина': 'Medical',
  'Мероприятия': 'Events',
  'Музыка и аудио': 'Music & Audio',
  'Новости и журналы': 'News & Magazines',
  'Образование': 'Education',
  'Персонализация': 'Personalization',
  'Погода': 'Weather',
  'Покупки': 'Shopping',
  'Приложения для часов': 'Wear OS apps',
  'Путешествия': 'Travel',
  'Работа': 'Work',
  'Развлечения': 'Entertainment',
  'Разное': 'Miscellaneous',
  'Связь': 'Communication',
  'Социальные': 'Social',
  'Спорт': 'Sports',
  'Стиль жизни': 'Lifestyle',
  'Финансы': 'Finance',
  'Фотография': 'Photography',
  'Циферблаты': 'Watch faces',
};

const List<String> companies = [
  'google',
  'microsoft',
  'meta',
  'apple',
  'amazon',
  'netflix',
  'spotify',
  'adobe',
  'telegram',
  'discord',
  'zoom',
  'slack',
  'dropbox',
  'evernote',
  'notion',
  'trello',
  'asana',
  'canva',
  'figma',
  'unity',
];

// Данные разработчиков
const List<String> developerCompanies = [
  'Google LLC',
  'Microsoft Corporation',
  'Meta Platforms, Inc.',
  'Apple Inc.',
  'Amazon.com, Inc.',
  'Netflix, Inc.',
  'Spotify AB',
  'Adobe Inc.',
  'Telegram FZ-LLC',
  'Discord Inc.',
  'Zoom Video Communications, Inc.',
  'Slack Technologies, LLC',
  'Dropbox, Inc.',
  'Evernote Corporation',
  'Notion Labs, Inc.',
  'Atlassian Pty Ltd',
  'Canva Pty Ltd',
  'Figma, Inc.',
  'Unity Technologies',
  'ByteDance Ltd.',
];

const List<String> developerAddresses = [
  '1600 Amphitheatre Parkway',
  'One Microsoft Way',
  '1 Hacker Way',
  'One Apple Park Way',
  '410 Terry Avenue North',
  '100 Winchester Circle',
  'Regeringsgatan 19',
  '345 Park Avenue',
  'Dubai Media City',
  '444 De Haro Street',
  '55 Almaden Boulevard',
  '500 Howard Street',
  '1800 Owens Street',
  '305 Walnut Street',
  '2300 Harrison Street',
  '350 Bush Street',
  '110 Kippax Street',
  '760 Market Street',
  '30 3rd Street',
  '2-36 Jiuxianqiao Road',
];

const List<String> developerCities = [
  'Mountain View, CA 94043',
  'Redmond, WA 98052',
  'Menlo Park, CA 94025',
  'Cupertino, CA 95014',
  'Seattle, WA 98109',
  'Los Gatos, CA 95032',
  'Stockholm, 111 57',
  'San Jose, CA 95110',
  'Dubai, UAE',
  'San Francisco, CA 94107',
  'San Jose, CA 95113',
  'San Francisco, CA 94105',
  'San Francisco, CA 94158',
  'Redwood City, CA 94063',
  'San Francisco, CA 94110',
  'San Francisco, CA 94104',
  'Surry Hills, NSW 2010',
  'San Francisco, CA 94102',
  'San Francisco, CA 94103',
  'Chaoyang District, Beijing 100015',
];

const List<String> developerCountries = [
  'United States',
  'United States',
  'United States',
  'United States',
  'United States',
  'United States',
  'Sweden',
  'United States',
  'United Arab Emirates',
  'United States',
  'United States',
  'United States',
  'United States',
  'United States',
  'United States',
  'United States',
  'Australia',
  'United States',
  'United States',
  'China',
];

const List<String> developerPhones = [
  '+1 650-253-0000',
  '+1 425-882-8080',
  '+1 650-543-4800',
  '+1 408-996-1010',
  '+1 206-266-1000',
  '+1 408-540-3700',
  '+46 8-611 26 30',
  '+1 408-536-6000',
  '+971 4 391 6666',
  '+1 415-723-5100',
  '+1 888-799-9666',
  '+1 415-630-7943',
  '+1 415-857-0150',
  '+1 650-257-0000',
  '+1 415-854-5152',
  '+1 415-701-1110',
  '+61 2 8335 0800',
  '+1 415-697-9000',
  '+1 415-539-3232',
  '+86 10 5765 1234',
];
