const Map<String, String> titleEnByRu = {
  'Новое обновление': 'New Update',
  'Выбор редакции': "Editor's Choice",
  'Рекомендуем': 'Recommended',
  'Событие недели': 'Event of the Week',
  'Эксклюзивно у нас': 'Exclusive for You',
  'Попробуйте сейчас': 'Try It Now',
  'Лидеры чартов': 'Top Charts',
  'Скидки на приложения': 'App Discounts',
  'Скидки на игры': 'Game Discounts',
  'Лучшее за месяц': 'Best of the Month',
  'Топ недели': 'Weekly Top',
  'Новинки недели': 'This Week’s New Releases',
  'Только у нас': 'Only Here',
  'Ограниченное время': 'Limited Time',
  'Специальное предложение': 'Special Offer',
  'Горячие скидки': 'Hot Deals',
  'Распродажа': 'Sale',
  'Бесплатно сегодня': 'Free Today',
  'Популярное': 'Trending',
  'В тренде': 'In Trend',
  'Для подписчиков': 'For Subscribers',
  'Премиум-подборка': 'Premium Picks',
  'Выбор пользователей': 'Users’ Choice',
  'Обновлено': 'Refreshed',
  'Свежие релизы': 'Fresh Releases',
  'Игры выходного': 'Weekend Games',
  'Книги недели': 'Books of the Week',
  'Читайте сейчас': 'Read Now',
  'Слушайте в дороге': 'Listen On the Go',
  'Для всей семьи': 'For the Whole Family',
  'Детям': 'For Kids',
  'Обучение и развитие': 'Learning & Growth',
  'Производительность': 'Productivity',
  'Творчество': 'Creativity',
  'Здоровье и фитнес': 'Health & Fitness',
  'Путешествия': 'Travel',
  'Музыка и звук': 'Music & Audio',
  'Фото и видео': 'Photo & Video',
  'Безопасность': 'Security',
  'Облако и синхронизация': 'Cloud & Sync',
  'Офлайн': 'Offline',
  'Без рекламы': 'No Ads',
};

const Map<String, String> tooltipEnByRu = {
  'Новинка': 'New',
  'Акция': 'Promo',
  'Рекомендуем': 'Recommended',
  'Хит': 'Hit',
  'Топ': 'Top',
  'Скидка': 'Discount',
  'Бесплатно': 'Free',
  'Ограничено': 'Limited',
  'Эксклюзив': 'Exclusive',
  'Обновлено': 'Updated',
  'Сегодня': 'Today',
  'Только сейчас': 'Now only',
  'Выбор дня': 'Pick of the day',
  'Подборка': 'Collection',
  'Спеццена': 'Special price',
  'Распродажа': 'Sale',
  'Финал сезона': 'Season finale',
  'Премиум': 'Premium',
  'Подписчикам': 'Subscribers',
  'Бонус': 'Bonus',
  'Подарок': 'Gift',
  'Новое': 'Fresh',
  'Горячее': 'Hot',
  'Тренд': 'Trending',
  'Редакция': 'Editors',
  'Лимит': 'Limited stock',
  '24 часа': '24 hours',
  'Выходные': 'Weekend',
  'Только в приложении': 'In-app only',
  'Ранний доступ': 'Early access',
  'Бета': 'Beta',
  'Обновление': 'Update',
};

const List<String> ruTitleVariants = <String>[
  'сегодня',
  'для вас',
  'прямо сейчас',
  'этой недели',
  'в этом месяце',
  'только сейчас',
  'не пропустите',
  'успейте',
  'ограниченное время',
  'специально для вас',
  'по подписке',
  'без рекламы',
  'с бонусом',
  'с подарком',
  'выбор редакции',
  'топ подборка',
  'новинки',
  'хиты продаж',
  'для всей семьи',
  'в дорогу',
  'дома',
  'на выходных',
  'до конца недели',
  'только здесь',
  'эксклюзив',
  'премиум',
  'бесплатно',
  'со скидкой',
  'обновлено',
  'свежий релиз',
  'только в приложении',
];

const List<String> enTitleVariants = <String>[
  'today',
  'for you',
  'right now',
  'this week',
  'this month',
  'limited time',
  'don’t miss',
  'hurry',
  'exclusive',
  'editors’ pick',
  'trending',
  'new release',
  'top picks',
  'family friendly',
  'on the go',
  'at home',
  'weekend deal',
  'ends soon',
  'only here',
  'premium',
  'free',
  'on sale',
  'updated',
  'subscriber only',
  'no ads',
  'with bonus',
  'best value',
  'staff favorite',
  'just dropped',
  'in-app only',
  'early access',
];

const List<String> ruDescriptionVariants = <String>[
  'Не пропустите актуальные предложения.',
  'Проверьте подборку и выберите лучшее.',
  'Откройте новинки и специальные предложения.',
  'Подборка обновляется регулярно.',
  'Удобный старт — в один тап.',
  'Найдите то, что подойдёт именно вам.',
  'Лучшие предложения в одном месте.',
  'Сэкономьте время и деньги.',
  'Попробуйте бесплатно или со скидкой.',
  'Только проверенные приложения и игры.',
  'Для работы, учёбы и отдыха.',
  'Смотрите детали внутри карточки.',
  'Акция действует ограниченное время.',
  'Добавьте в список желаний и не упустите.',
  'Рекомендуем обновить приложение до последней версии.',
  'Новые материалы уже доступны.',
  'Слушайте, читайте и играйте где угодно.',
  'Синхронизация между устройствами.',
  'Безопасная оплата и быстрый доступ.',
  'Персональные рекомендации на основе ваших интересов.',
  'Выбор редакции и отзывы пользователей.',
  'Скидки до конца недели.',
  'Подарок при первой покупке.',
  'Расширенная пробная версия.',
  'Поддержка на русском языке.',
];

const List<String> enDescriptionVariants = <String>[
  'Do not miss the latest offers.',
  'Check the selection and pick the best.',
  'Discover fresh picks and special deals.',
  'The collection updates regularly.',
  'Get started with a single tap.',
  'Find what fits you best.',
  'Top offers in one place.',
  'Save time and money.',
  'Try for free or at a discount.',
  'Curated apps and games only.',
  'For work, study, and play.',
  'See details on the card.',
  'Limited-time promotion.',
  'Add to your wishlist so you don’t miss out.',
  'Update the app for the best experience.',
  'New content is live now.',
  'Read, listen, and play anywhere.',
  'Sync across your devices.',
  'Secure checkout and instant access.',
  'Personalized picks based on your interests.',
  'Editor picks and user reviews.',
  'Discounts through the weekend.',
  'Gift with your first purchase.',
  'Extended trial available.',
  'Full English support.',
  'Offline mode where available.',
];

const List<String> eventDescriptionRuLines = <String>[
  'Специальное событие: бонусы и скидки только в этот период.',
  'Участвуйте в акции и получите дополнительные преимущества.',
  'Ограниченная серия предложений — количество промокодов ограничено.',
  'Событие для новых пользователей: расширенный пробный период.',
  'Сезонная распродажа: успейте оформить подписку по выгодной цене.',
  'Эксклюзивные материалы и ранний доступ к обновлениям.',
  'Праздничная подборка: подарки и сюрпризы внутри приложения.',
  'Турнир недели: соревнуйтесь с друзьями и поднимайтесь в рейтинге.',
  'Фестиваль инди-игр: откройте для себя новые проекты.',
  'Книжная ярмарка: скидки на аудио и электронные издания.',
  'Фокус на продуктивности: курсы и инструменты в одном месте.',
  'Здоровье и спорт: челленджи и напоминания на месяц.',
  'Творческий марафон: шаблоны, эффекты и вдохновение.',
  'Путешествия без стресса: офлайн-карты и гиды со скидкой.',
  'Музыкальная волна: подборки плейлистов и подкастов.',
  'Фото-сезон: пресеты и облако для ваших снимков.',
  'Безопасность данных: усиленная защита по промокоду.',
  'Семейный режим: контент для детей и родителей вместе.',
  'Обучение языкам: интенсив на две недели с тренажёром.',
  'Ночь настольных игр: локальный мультиплеер и бонусы.',
  'Киберспортивный уик-энд: трансляции и награды зрителям.',
  'Ретро-коллекция: классика жанра по сниженной цене.',
  'Зелёная пятница: экологичные приложения и донаты.',
  'Стартап-неделя: инструменты для команд и фрилансеров.',
  'Дизайн и UI: наборы иконок и шрифтов в подарок.',
  'Медитация и сон: аудиопрограммы с персональным планом.',
  'Кулинарный фестиваль: рецепты и таймеры шаг за шагом.',
  'Авто и навигация: пробки, парковки и маршруты со скидкой.',
  'Финансы и бюджет: кэшбэк при оплате из приложения.',
  'Облачное хранилище: удвоенный объём на первый месяц.',
  'Стриминг без рекламы: пробный премиум на выходные.',
  'Чтение вслух: синтез речи и крупный шрифт бесплатно.',
  'AR-опыт: фильтры и сцены только по ссылке события.',
  'Кооператив в сети: пригласите друга — бонус обоим.',
  'Летняя коллекция: яркие темы оформления интерфейса.',
  'Зимняя распродажа: согревающие скидки на подписки.',
  'День студента: учебные приложения с промокодом.',
  'Чёрная пятница: максимальные скидки года в каталоге.',
  'День матери: семейные подборки и подарочные сертификаты.',
  'День отца: гаджеты, игры и хобби в одной витрине.',
  'Годовщина сервиса: благодарность пользователям и розыгрыш.',
  'Ранний доступ к бете: ваш отзыв влияет на продукт.',
  'Коллаборация с брендом: уникальные скины и стикеры.',
  'Локальное событие: акции партнёров в вашем регионе.',
  'Эко-челлендж: сажаем деревья за активность в приложении.',
  'Ночь кино: фильмы и сериалы с пробным просмотром.',
  'Спортзал дома: тренировки без оборудования, скидка на план.',
  'Путешествие выходного дня: гайды и аудиоэкскурсии.',
  'Музей онлайн: виртуальные туры и аудиогиды со скидкой.',
  'Код недели: введите в настройках для бонуса.',
];

const List<String> eventDescriptionEnLines = <String>[
  'Special event: bonuses and discounts for a limited time only.',
  'Join the promo and unlock extra perks.',
  'Limited run — promo codes are capped.',
  'New-user event: extended trial period.',
  'Seasonal sale: grab a subscription at a better price.',
  'Exclusive content and early access to updates.',
  'Holiday picks: gifts and surprises inside the app.',
  'Weekly tournament: compete with friends and climb the ranks.',
  'Indie game festival: discover fresh titles.',
  'Book fair: deals on audiobooks and e-books.',
  'Productivity focus: courses and tools in one place.',
  'Health & fitness: monthly challenges and reminders.',
  'Creative marathon: templates, effects, and inspiration.',
  'Travel made easy: offline maps and guides on sale.',
  'Music wave: playlists and podcast picks.',
  'Photo season: presets and cloud for your shots.',
  'Data security: stronger protection with a promo code.',
  'Family mode: content for kids and parents together.',
  'Language sprint: two-week intensive with a trainer.',
  'Board-game night: local multiplayer and bonuses.',
  'Esports weekend: streams and rewards for viewers.',
  'Retro collection: genre classics at a discount.',
  'Green Friday: eco apps and donation perks.',
  'Startup week: tools for teams and freelancers.',
  'Design & UI: icon packs and fonts as a gift.',
  'Meditation & sleep: audio programs with a personal plan.',
  'Cooking festival: recipes and step-by-step timers.',
  'Cars & navigation: traffic, parking, and routes on sale.',
  'Finance & budget: cashback when you pay in-app.',
  'Cloud storage: double space for the first month.',
  'Ad-free streaming: premium trial for the weekend.',
  'Read aloud: speech synthesis and large type for free.',
  'AR experience: filters and scenes via the event link.',
  'Online co-op: invite a friend — a bonus for both.',
  'Summer collection: bright UI themes.',
  'Winter sale: cozy discounts on subscriptions.',
  'Student day: study apps with a promo code.',
  'Black Friday: biggest discounts of the year in the catalog.',
  "Mother's Day: family picks and gift cards.",
  "Father's Day: gadgets, games, and hobbies in one showcase.",
  'Service anniversary: thank-you perks and a giveaway.',
  'Early beta access: your feedback shapes the product.',
  'Brand collab: unique skins and stickers.',
  'Local event: partner deals in your region.',
  'Eco challenge: we plant trees for your in-app activity.',
  'Movie night: films and series with a trial watch.',
  'Home gym: no-equipment workouts, plan on sale.',
  'Weekend trip: guides and audio tours.',
  'Museum online: virtual tours and discounted audio guides.',
  'Code of the week: enter in settings for a bonus.',
];

const List<String> ruEventDescriptionSuffixes = <String>[
  'Действует ограниченное время.',
  'Условия — на странице события.',
  'Количество активаций ограничено.',
  'Проверьте детали в приложении.',
  'Только для авторизованных пользователей.',
  'Можно комбинировать с другими акциями.',
  'Промокод вводится при оплате.',
  'Предложение не суммируется с подарочными картами.',
  'География акции может отличаться.',
  'Актуально до конца недели.',
  'Следите за обновлениями раздела.',
  'Участие не требует подписки.',
  'Бонус начисляется автоматически.',
  'Подарок доступен один раз на аккаунт.',
  'Расширенные условия — в справке.',
  'Присоединяйтесь к сообществу внутри приложения.',
  'Рейтинг и награды — в профиле события.',
  'Совместимо с офлайн-режимом где доступно.',
  'Для семейного доступа может потребоваться настройка.',
  'Отмена подписки не влияет на уже полученный бонус.',
];

const List<String> enEventDescriptionSuffixes = <String>[
  'Limited time only.',
  'See the event page for terms.',
  'Redemptions are capped.',
  'Check details in the app.',
  'Signed-in users only.',
  'May stack with select offers.',
  'Enter the promo code at checkout.',
  'Not valid with gift cards.',
  'Region restrictions may apply.',
  'Valid through this weekend.',
  'Watch this section for updates.',
  'No subscription required to join.',
  'Bonus applies automatically.',
  'One gift per account.',
  'Full terms in the help center.',
  'Join the in-app community.',
  'Leaderboards and rewards in the event profile.',
  'Offline mode supported where available.',
  'Family sharing may require setup.',
  'Canceling a plan does not revoke granted perks.',
];

const List<String> bannerImages = [
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/banners/images/banner1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/banners/images/banner2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/banners/images/banner3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/banners/images/banner4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/banners/images/banner5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/banners/images/banner6.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/banners/images/banner7.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/banners/images/banner8.webp',
];
