const List<String> titleWords = [
  'Возвращенный',
  'Неведомый',
  'Затерянный',
  'Финальный',
  'Хронический',
  'Кровавый',
  'Призрачный',
  'Космический',
  'Мистический',
  'Древний',
  'Тайный',
  'Ледяной',
  'Огненный',
  'Темный',
  'Светлый',
  'Великий',
  'Магический',
  'Скрытый',
  'Цифровой',
  'Бесконечный',
  'Последний',
  'Железный',
  'Золотой',
  'Стеклянный',
  'Песчаный',
  'Морской',
  'Звездный',
  'Крипто',
  'Безумный',
  'Дикий',
  'Тихий',
  'Громкий',
  'Облачный',
  'Расколотый',
  'Забытый',
  'Вечный',
  'Глубокий',
  'Высокий',
  'Быстрый',
  'Запретный',
  'Ветхий',
  'Истинный',
  'Пророческий',
  'Зловещий',
  'Покинутый',
  'Роковой',
  'Королевский',
  'Механический',
  'Трофейный',
  'Яростный',
  'Солнечный',
  'Лунныый',
  'Торжественный',
  'Смертельный',
  'Утерянный',
  'Небесный',
  'Подземный',
  'Земной',
  'Алмазный',
  'Нефритовый',
  'Снежный',
  'Цветочный',
  'Греховный',
  'Священный',
  'Грядущий',
];

const List<String> titleWordsEn = [
  'Returned',
  'Unknown',
  'Lost',
  'Final',
  'Chronic',
  'Bloody',
  'Phantom',
  'Cosmic',
  'Mystic',
  'Ancient',
  'Secret',
  'Icy',
  'Blazing',
  'Dark',
  'Bright',
  'Great',
  'Magical',
  'Hidden',
  'Digital',
  'Endless',
  'Last',
  'Iron',
  'Golden',
  'Glass',
  'Sandy',
  'Marine',
  'Starry',
  'Crypto',
  'Mad',
  'Wild',
  'Quiet',
  'Loud',
  'Cloudy',
  'Cracked',
  'Forgotten',
  'Eternal',
  'Deep',
  'Tall',
  'Fast',
  'Forbidden',
  'Dilapidated',
  'True',
  'Prophetic',
  'Ominous',
  'Abandoned',
  'Fateful',
  'Royal',
  'Mechanical',
  'Trophy',
  'Furious',
  'Sunny',
  'Lunar',
  'Grand',
  'Deadly',
  'Misplaced',
  'Heavenly',
  'Underground',
  'Earthly',
  'Diamond',
  'Jade',
  'Snowy',
  'Flowered',
  'Sinful',
  'Sacred',
  'Upcoming',
];

const List<String> suffixWords = [
  'Меч',
  'Арена',
  'Наследие',
  'Исход',
  'Проект',
  'Война',
  'Вторжение',
  'Пустота',
  'Эхо',
  'Квест',
  'Сага',
  'Дрифт',
  'Убежище',
  'Мир',
  'Бастион',
  'Портал',
  'Крепость',
  'Лабиринт',
  'Трон',
  'Империя',
  'Флот',
  'Планета',
  'Корабль',
  'Клинок',
  'Щит',
  'Заклинание',
  'Руна',
  'Легенда',
  'Герой',
  'Рыцарь',
  'Вор',
  'Призрак',
  'Сон',
  'Замок',
  'Королевство',
  'Долина',
  'Гора',
  'Остров',
  'Маяк',
  'Руины',
  'Башня',
  'Скала',
  'Огонь',
  'Вода',
  'Земля',
  'Ветер',
  'Кровь',
  'Тень',
  'Свет',
  'Жизнь',
  'Смерть',
  'Судьба',
  'Аватар',
  'Феникс',
  'Дракон',
  'Грифон',
  'Минотавр',
  'Головоломка',
  'Код',
  'Матрица',
  'Протокол',
  'Терминал',
  'Звезда',
  'Орбита',
  'Галактика',
  'Сектор',
  'Побег',
  'Поиск',
  'Реликвия',
  'Артефакт',
  'Храм',
  'Гробница',
  'Трасса',
];

const List<String> suffixWordsEn = [
  'Sword',
  'Arena',
  'Legacy',
  'Exit',
  'Project',
  'War',
  'Invasion',
  'Void',
  'Echo',
  'Quest',
  'Saga',
  'Drift',
  'Sanctuary',
  'World',
  'Bastion',
  'Portal',
  'Fortress',
  'Labyrinth',
  'Throne',
  'Empire',
  'Fleet',
  'Planet',
  'Ship',
  'Blade',
  'Shield',
  'Spell',
  'Rune',
  'Legend',
  'Hero',
  'Knight',
  'Thief',
  'Ghost',
  'Dream',
  'Castle',
  'Kingdom',
  'Valley',
  'Mountain',
  'Island',
  'Lighthouse',
  'Ruins',
  'Tower',
  'Rock',
  'Fire',
  'Water',
  'Earth',
  'Wind',
  'Blood',
  'Shadow',
  'Light',
  'Life',
  'Death',
  'Fate',
  'Avatar',
  'Phoenix',
  'Dragon',
  'Griffin',
  'Minotaur',
  'Puzzle',
  'Code',
  'Matrix',
  'Protocol',
  'Terminal',
  'Star',
  'Orbit',
  'Galaxy',
  'Sector',
  'Escape',
  'Search',
  'Relic',
  'Artifact',
  'Temple',
  'Tomb',
  'Track',
];

const List<String> genres = [
  'arcade',
  'trivia',
  'puzzle',
  'racing',
  'casino',
  'casual',
  'card',
  'music',
  'board',
  'educational',
  'adventure',
  'rpg',
  'simulation',
  'word',
  'sports',
  'strategy',
  'action',
  'fighting',
  'indie',
  'shooter',
  'horror',
];

const List<String> genresRu = [
  'Аркады',
  'Викторины',
  'Головоломки',
  'Гонки',
  'Казино',
  'Казуальные',
  'Карточные',
  'Музыка',
  'Настольные',
  'Обучающие',
  'Приключения',
  'RPG',
  'Симуляторы',
  'Слова',
  'Спорт',
  'Стратегии',
  'Экшен',
  'Драки',
  'Инди',
  'Шутеры',
  'Хоррор',
];

const List<String> gameTags = [
  'survival',
  'fantasy',
  'medieval',
  'co-op',
  'open_world',
  'indie',
  'multiplayer',
  'story_rich',
  'cyberpunk',
  'zombie',
  'sci-fi',
  'roguelike',
  '2d',
  '3d',
  'pixel_art',
  'retro',
  'horror',
  'hardcore',
  'casual',
  'free',
  'paid',
  'crafting',
  'turn_based',
  'real_time',
  'economy',
  'building',
  'war',
  'exploration',
  'anime',
  'steampunk',
  'vr',
  'pvp',
  'pve',
  'cinematic',
  'challenging',
  'relaxing',
  'procedural',
  'crossplatform',
  'realistic',
  'stylized',
  'abstract',
  'minimalist',
  'post_apocalyptic',
  'esports',
  'offline',
  'low_price',
];

const List<String> gameTagsRu = [
  'выживание',
  'фэнтези',
  'средневековье',
  'кооператив',
  'открытый мир',
  'инди',
  'мультиплеер',
  'богатый сюжет',
  'киберпанк',
  'зомби',
  'научная фантастика',
  'рогалик',
  '2D',
  '3D',
  'пиксель-арт',
  'ретро',
  'хоррор',
  'хардкор',
  'казуальная',
  'бесплатно',
  'платно',
  'крафтинг',
  'пошаговые',
  'в реальном времени',
  'экономика',
  'строительство',
  'война',
  'исследование',
  'аниме',
  'стимпанк',
  'VR',
  'PvP',
  'PvE',
  'кинематографичность',
  'сложность',
  'расслабляющий',
  'процедурная генерация',
  'кроссплатформенность',
  'реалистичный',
  'стилизованный',
  'абстрактный',
  'минимализм',
  'постапокалипсис',
  'киберспорт',
  'офлайн',
  'низкая цена',
];

const List<String> kidsTags = [
  'math',
  'drawing',
  'alphabet',
  'letters',
  'numbers',
  'languages',
  'health',
  'logic',
  'creativity',
  'fairy_tales',
  'cartoons',
  'family',
];

const List<String> kidsTagsRu = [
  'математика',
  'рисование',
  'алфавит',
  'буквы',
  'цифры',
  'языки',
  'здоровье',
  'логика',
  'творчество',
  'сказки',
  'мультфильмы',
  'семья',
];

const List<String> icons = [
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/afk_arena.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/among_us.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/asphalt.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/best_fiends.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/bleach.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/block_blast.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/blue_archive.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/brawl_stars.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/burrito_bisone.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/chess.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/clash_of_clans.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/clash_royale.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/cookierun.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/cut_the_rope.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/dead_cells.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/divineko.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/don_t_starve.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/doom.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/dumb_ways_to_die.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/fluffy_fall.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/fnaf.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/free_fire_max.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/friday_night_funkin.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/fruit_ninja.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/gardenscapes.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/genshin_impact.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/geometry_dash.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/hay_day.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/hello_kitty_my_dream_store.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/honkai_star_rail.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/identity_v.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/league_of_legends.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/limbo.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/minecraft.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/monopoly_go.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/muse_dash.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/my_singing_monsters.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/my_talking_tom_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/plants_vs_zombies_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/pokemon_go.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/pubg_mobile.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/rainbow_six_mobile.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/red_ball_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/roblox.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/skullgirls.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/solo_leveling_arise.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/standoff.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/stardew_valley.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/swamp_attack.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/tasty_planet.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/teablin_teashop.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/temple_run.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/terraria.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/the_battle_cats.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/tomb_of_the_mask.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/icons/games_icons/zenless_zone_zero.webp',
];

const List<String> horizontalScreenshots = [
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/block_blast_horiz_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/cats_and_soup_horiz_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/cats_and_soup_horiz_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/cats_and_soup_horiz_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/cats_and_soup_horiz_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/cats_and_soup_horiz_5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/cats_and_soup_horiz_6.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/cats_and_soup_horiz_7.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/plants_vs_zombies_2_horiz_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/plants_vs_zombies_2_horiz_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/plants_vs_zombies_2_horiz_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/plants_vs_zombies_2_horiz_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/plants_vs_zombies_2_horiz_5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/plants_vs_zombies_2_horiz_6.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/plants_vs_zombies_2_horiz_7.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/rfee_fire_horiz_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/rfee_fire_horiz_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/rfee_fire_horiz_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/rfee_fire_horiz_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/rfee_fire_horiz_5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/rfee_fire_horiz_6.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/stardew_valley_horiz_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/stardew_valley_horiz_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/stardew_valley_horiz_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/stardew_valley_horiz_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/stardew_valley_horiz_5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/stardew_valley_horiz_6.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/subway_serfers_horiz1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/subway_surfers_horiz2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/tasty_planet_horiz_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/tasty_planet_horiz_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/tasty_planet_horiz_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/tasty_planet_horiz_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/tasty_planet_horiz_5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/terraria_horiz_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/terraria_horiz_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/terraria_horiz_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/terraria_horiz_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/terraria_horiz_5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/terraria_horiz_6.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/terraria_horiz_7.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/the_battle_cats_horiz_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/the_battle_cats_horiz_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/the_battle_cats_horiz_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/the_battle_cats_horiz_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/the_battle_cats_horiz_5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/the_battle_cats_horiz_6.webp',
];

const List<String> verticalScreenshots = [
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/animal_restaurant_vert_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/animal_restaurant_vert_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/animal_restaurant_vert_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/animal_restaurant_vert_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/animal_restaurant_vert_5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/animal_restaurant_vert_6.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/block_blast_vert_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/block_blast_vert_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/block_blast_vert_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/block_blast_vert_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/roblox_vert_1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/roblox_vert_2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/roblox_vert_3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/roblox_vert_4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/roblox_vert_5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/subway_surfers_vert1.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/subway_surfers_vert2.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/subway_surfers_vert3.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/subway_surfers_vert4.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/subway_surfers_vert5.webp',
  'https://fglkdacurfxnwutkgoza.supabase.co/storage/v1/object/public/products/screenshots/games_screenshots/the_battle_cats_vert_1.webp',
];

final List<int> ageRatings = [3, 5, 6, 8, 9, 12, 16, 18];

const List<String> ageRatingReasons = [
  'Насилие',
  'Страх',
  'Сцены сексуального характера',
  'Наркотики',
  'Сквернословие',
  'Азартные игры',
  'Дискриминация',
  'Внутриигровые покупки',
  'Взаимодействие пользователей',
];

const List<String> ageRatingReasonsEn = [
  'Violence',
  'Fear',
  'Sexual content',
  'Drugs',
  'Profanity',
  'Gambling',
  'Discrimination',
  'In-app purchases',
  'User interaction',
];

const List<String> modes = ['Single-player', 'Multiplayer', 'Co-op'];

const List<String> achievementTitlesRu = [
  'Первый шаг',
  'Без единой ошибки',
  'Мастер комбо',
  'Босс повержен',
  'Легендарная победа',
  'Исследователь мира',
  'Скоростное прохождение',
  'Коллекционер',
  'Ни шагу назад',
  'Победа без урона',
  'Командный игрок',
  'Серия побед',
];

const List<String> achievementTitlesEn = [
  'First Steps',
  'Flawless Run',
  'Combo Master',
  'Boss Defeated',
  'Legendary Victory',
  'World Explorer',
  'Speedrun',
  'Collector',
  'No Retreat',
  'No-Damage Win',
  'Team Player',
  'Win Streak',
];

// Данные разработчиков игр
const List<String> developerCompanies = [
  'Rockstar Games, Inc.',
  'Electronic Arts Inc.',
  'Activision Publishing, Inc.',
  'Ubisoft Entertainment SA',
  'Take-Two Interactive Software, Inc.',
  'Nintendo Co., Ltd.',
  'Sony Interactive Entertainment LLC',
  'Microsoft Studios',
  'Blizzard Entertainment, Inc.',
  'Epic Games, Inc.',
  'Valve Corporation',
  'Square Enix Co., Ltd.',
  'Bandai Namco Entertainment Inc.',
  'Capcom Co., Ltd.',
  'Sega Corporation',
  'Konami Digital Entertainment',
  'CD Projekt S.A.',
  'Bethesda Softworks LLC',
  'Supercell Oy',
  'miHoYo Co., Ltd.',
];

const List<String> developerAddresses = [
  '110 W 44th St',
  '209 Redwood Shores Parkway',
  '3100 Ocean Park Boulevard',
  '28 Rue Armand Carrel',
  '622 Broadway',
  '11-1 Kamitoba Hokotate-cho',
  '2207 Bridgepointe Parkway',
  'One Microsoft Way',
  '16215 Alton Parkway',
  '620 Crossroads Blvd',
  '10400 NE 4th Street',
  '6-27-30 Shinjuku',
  '5-37-8 Shiba',
  '3-1-3 Uchihirano-machi',
  '1-2-12 Higashishinagawa',
  '1-11-1 Ginza',
  'Jagiellonska 74',
  '1370 Piccard Drive',
  'Itämerenkatu 11',
  'No. 1 Xibeiwang East Road',
];

const List<String> developerCities = [
  'New York, NY 10036',
  'Redwood City, CA 94065',
  'Santa Monica, CA 90405',
  'Montreuil, 93100',
  'New York, NY 10012',
  'Minami-ku, Kyoto 601-8501',
  'San Mateo, CA 94404',
  'Redmond, WA 98052',
  'Irvine, CA 92618',
  'Cary, NC 27518',
  'Bellevue, WA 98004',
  'Shinjuku-ku, Tokyo 160-8430',
  'Minato-ku, Tokyo 108-0014',
  'Chuo-ku, Osaka 540-0037',
  'Shinagawa-ku, Tokyo 140-8583',
  'Chuo-ku, Tokyo 104-0061',
  'Warsaw, 03-301',
  'Rockville, MD 20850',
  'Helsinki, 00180',
  'Haidian District, Beijing 100193',
];

const List<String> developerCitiesRu = [
  'Нью-Йорк, штат Нью-Йорк 10036',
  'Редвуд-Сити, штат Калифорния 94065',
  'Санта-Моника, штат Калифорния 90405',
  'Монрей, 93100',
  'Нью-Йорк, штат Нью-Йорк 10012',
  'Минами-ку, Киото 601-8501',
  'Сан-Матео, штат Калифорния 94404',
  'Редмонд, штат Вашингтон 98052',
  'Ирвин, штат Калифорния 92618',
  'Кэри, штат Северная Каролина 27518',
  'Белвью, штат Вашингтон 98004',
  'Синдзюку-ку, Токио 160-8430',
  'Минато-ку, Токио 108-0014',
  'Тюо-ку, Осака 540-0037',
  'Синагава-ку, Токио 140-8583',
  'Тюо-ку, Токио 104-0061',
  'Варшава, 03-301',
  'Роквилл, штат Мэриленд 20850',
  'Хельсинки, 00180',
  'Хайдяньский район, Пекин 100193',
];

const List<String> developerCountries = [
  'United States',
  'United States',
  'United States',
  'France',
  'United States',
  'Japan',
  'United States',
  'United States',
  'United States',
  'United States',
  'United States',
  'Japan',
  'Japan',
  'Japan',
  'Japan',
  'Japan',
  'Poland',
  'United States',
  'Finland',
  'China',
];

const Map<String, String> developerCountryRuByEn = {
  'United States': 'Соединенные Штаты',
  'France': 'Франция',
  'Japan': 'Япония',
  'Poland': 'Польша',
  'Finland': 'Финляндия',
  'China': 'Китай',
};

final developerCountriesRu = developerCountries
    .map((c) => developerCountryRuByEn[c] ?? c)
    .toList();

const List<String> developerPhones = [
  '+1 646-817-2429',
  '+1 650-628-1500',
  '+1 310-255-2000',
  '+33 1 48 18 50 00',
  '+1 212-334-6633',
  '+81 75-662-9600',
  '+1 650-655-8000',
  '+1 425-882-8080',
  '+1 949-955-1380',
  '+1 919-854-0070',
  '+1 425-889-9642',
  '+81 3-5292-1200',
  '+81 3-6744-5000',
  '+81 6-6920-3600',
  '+81 3-6864-2200',
  '+81 3-3573-1111',
  '+48 22 519 69 00',
  '+1 301-926-8300',
  '+358 9 4247 5200',
  '+86 10-5765-2888',
];

const List<String> permissions = [
  'Камера',
  'Микрофон',
  'Геолокация',
  'Контакты',
  'Хранилище',
  'Уведомления',
  'Bluetooth',
  'Информация о Wi-Fi подключении',
  'Идентификатор устройства и данные о вызовах',
  'Неограниченный доступ к Интернету',
  'Просмотр сетевых подключений',
  'Запуск при включении устройства',
  'Предотвращение спящего режима',
  'Управление вибросигналом',
  'Чтение содержимого USB-накопителя',
  'Изменение или удаление содержимого USB-накопителя',
  'Получение данных из Интернета',
  'Play Install Referrer API',
  'Запуск фоновых служб',
  'Разрешение на рекламный идентификатор',
  'Наложение поверх других окон',
  'Доступ к медиафайлам',
  'Использование биометрических данных',
  'Сервисы выставления счетов Google Play',
  'Доступ к данным о физической активности',
  'Чтение настроек синхронизации',
  'Запуск при загрузке',
];

const List<String> permissionsEn = [
  'Camera',
  'Microphone',
  'Location',
  'Contacts',
  'Storage',
  'Notifications',
  'Bluetooth',
  'Wi-Fi connection information',
  'Device ID and call data',
  'Full internet access',
  'View network connections',
  'Start at device boot',
  'Prevent sleep',
  'Control vibration',
  'Read USB storage contents',
  'Modify or delete USB storage contents',
  'Retrieve data from the internet',
  'Play Install Referrer API',
  'Run background services',
  'Permission to the advertising identifier',
  'Appear on top of other apps',
  'Access to media files',
  'Use biometric data',
  'Google Play Billing services',
  'Access to physical activity data',
  'Read sync settings',
  'Start at boot',
];

// Жанры, которые чаще выпадают у детских игр
const List<String> kidsGenres = [
  'casual',
  'educational',
  'puzzle',
  'arcade',
  'music',
  'word',
  'trivia',
  'board',
  'simulation',
  'adventure',
];

final Map<String, String> ageRatingReasonsEnByRu = {
  for (int i = 0; i < ageRatingReasons.length; i++)
    ageRatingReasons[i]: ageRatingReasonsEn[i],
};

final Map<String, String> permissionsEnByRu = {
  for (int i = 0; i < permissions.length; i++) permissions[i]: permissionsEn[i],
};

final Map<String, String> genresRuByEn = {
  for (int i = 0; i < genres.length; i++) genres[i]: genresRu[i],
};

final Map<String, String> gameTagsRuByEn = {
  for (int i = 0; i < gameTags.length; i++) gameTags[i]: gameTagsRu[i],
};

final Map<String, String> kidsTagsRuByKey = {
  for (int i = 0; i < kidsTags.length; i++) kidsTags[i]: kidsTagsRu[i],
};

final Map<String, String> achievementTitlesEnByRu = {
  for (int i = 0; i < achievementTitlesRu.length; i++)
    achievementTitlesRu[i]: achievementTitlesEn[i],
};

const List<String> languages = [
  'RU',
  'EN',
  'ES',
  'FR',
  'DE',
  'IT',
  'PT',
  'ZH',
  'JA',
  'KO',
];
